meta:
  app_id:
  display_name:
  version:
  vendor: Shopify
  support_url:
  description:
  contact_email:
  #Future: Cost info, release notes?

runtime: node11

#Rely on conventions for lifecycle (install, upgrade, uninstall, etc.)
#i.e. install.js, upgrade.js, uninstall.js for node11
defaults:
    permissions:
      -READ_WRITE_KV
      -READ_DOCUMENTS
      -<READ|WRITE>_<SVC>
    environment:
      ENV_VAR1: @my_secret@ #inherit defaults

webhooks:
  foo:
    #Function spec
    entry_point: functions.doFoo
    environment:
      ENV_VAR2: 2 #inherit defaults
    permissions:
      -WRITE_ZAIUS_ORDERS #inherits defaults
    triggers:
      interval: x seconds | minutes | hours | days | weeks | months
      cron: <cron_expression>
      #Always exposed as a webhook
      #Future: events
    size: small | medium | large
    visibility: public | private

jobs:
  importMyData:
    entry_point: jobs.importMyData
    triggers:
      interval: x seconds | minutes | hours | days | weeks | months
      cron: <cron_expression>
      #Always allow via webhook for testing/debugging
      #Future: events
    runtime: ruby@2.10
    permissions:
    environment:
    timeout: 10 minutes #Can apply a limit to this at compile time to sanity check
    size: small | medium | large
    visibility: public | private
