meta:
  app_id:
  display_name:
  version:
  vendor: Shopify
  support_url:
  summary:
  contact_email:

runtime: node11

#Rely on conventions for lifecycle (install, upgrade, uninstall, etc.)
#i.e. install.js, upgrade.js, uninstall.js for node11
defaults:
    permissions:
      -READ_WRITE_KV
      -READ_DOCUMENTS
      -<READ|WRITE>_<SVC>
    environment:
      ENV_VAR1: @my_secret@ #inherit defaults

functions:
  foo:
    method: POST
    entry_point: functions.doFoo
    summary:

jobs:
  importMyData:
    entry_point: jobs.importMyData
    triggers:
      interval: x seconds | minutes | hours | days | weeks | months
      cron: <cron_expression>
      #Always allow via webhook for testing/debugging
      #Future: events
    timeout: 10 minutes #Can apply a limit to this at compile time to sanity check
