/**
 * A set of identifiers that uniquely identify a user.
 */
export interface Identifiers {
  /**
   * The user's email if known
   */
  email?: string;
  /**
   * Zaius's globally unique identifier generated by SDKs such as the Javascript SDK.
   * Only use if you are forwarding a VUID generated by Zaius.
   */
  vuid?: string;
  /**
   * Other identifiers known to the account, such as `my_app_cart_token`
   */
  [field: string]: string | undefined;
}
