/**
 * The default layout of the docs generated by typedoc-plugin-markdown does not import well into readme.
 * The main issue is that rdme imports all files at the same level and does not follow folder structure.
 *
 * The script makes the following changes to the docs generated by typedoc-plugin-markdown
 * - merges README.md (custom description from README.md file) and modules.md (table of content) into one file
 *   and puts the file at the top of the category
 * - add unique slugs to all files in format 'node-sdk-api-reference-<parent>' (for top category items) or 'node-sdk-api-reference-<parent>-<child>' (for nexted items)
 * - adds parentDocSlug parameter to frontmatter to form a hierarchy where top level items are:
 *   Overview, an item for each global element (classes, enums, functions, interfaces, types, variables),
 *   'namespace: <namespace_name>' for each namespace
 *   and '<namespace_name> <element>' for each element within the namespace (classes, enums, functions, interfaces, types, variables)
 *   Namespaces get flatten, e.g. namespaces Zaius and Zaius.Api3 are at the same level.
 */

const slugify = require("slugify");
const fs = require('fs');
const path = require('path');

function getFrontMatterProperty(file, property) {
    let content = fs.readFileSync(file, 'utf8')
    const re = new RegExp(`${property}: "?([^"$\n]+)("|$)`, "gm");

    return re.exec(content)[1];
}

let category = getFrontMatterProperty('./docs/README.md', "category");
let hidden = getFrontMatterProperty('./docs/README.md', "hidden");

function addFrontMatterProperty(file, property) {
    let content = fs.readFileSync(file, 'utf8')
    let updatedContent = content.replace(/---\n/, `---\n${property}\n`);

    fs.writeFileSync(file, updatedContent);
}

function removeFrontMatterProperty(file, property) {
    let content = fs.readFileSync(file, 'utf8')
    let updatedContent = content.replace(/title: .*\n/, ``);

    fs.writeFileSync(file, updatedContent);
}

function createFolderAndMoveDocs(baseDir, folderName, namespace, title) {
    let files = fs.readdirSync(baseDir+ '/' + folderName, { withFileTypes: true });
    let parentDocSlug = slugify(`node-sdk API reference ${title}`, {lower: true, strict: true});

    let header = `---
title: "${title}"
category: "${category}"
slug: "${parentDocSlug}"
hidden: ${hidden}
---

### ${title}

`;

    let toc = files
    .filter(f => f.isFile())
    .map(f => {
        const titleRe = /title: (.+).*/g;
        let title = titleRe.exec(fs.readFileSync(baseDir + '/' + folderName + "/" + f.name, 'utf8'))[1];
        return "- [" + title + "](" + folderName + "/" + f.name + ")"
    })
    .join('\n')

    fs.writeFileSync(
        baseDir + '/' + folderName +'.md',
        header + toc
    );

    // add slug parameter to frontmatter in every file in folder
    let order = 100;
    files.filter(f => f.isFile()).forEach(f => {
        let file = baseDir+ '/' + folderName + "/" + f.name;

        let childTitle = getFrontMatterProperty(file, 'title')
        let slug = slugify(`node-sdk API reference ${title} ${childTitle}`, {lower: true, strict: true})

        addFrontMatterProperty(file, `slug: "${slug}"`);
        addFrontMatterProperty(file, `parentDocSlug: "${parentDocSlug}"`);
        addFrontMatterProperty(file, `order: "${order++}"`);
    });
}

function mergeReadmeAndGlobals() {
    let toc = fs.readFileSync('./docs/globals.md', 'utf8')
    fs.rmSync('./docs/globals.md');

    toc = toc.replace(/.*## Index/s, '');

    let readme = fs.readFileSync('./docs/README.md', 'utf8') + "\n## Index" + toc;
    fs.writeFileSync('./docs/README.md', readme);
}

function flattenNamespace(folder, namespace, fullNamespaceName) {
    const formFile = `./docs/${folder}/README.md`;
    removeFrontMatterProperty(formFile, 'title');
    addFrontMatterProperty(formFile, `title: "namespace: ${fullNamespaceName}"`);

    let formDocSlug = slugify(`node-sdk API reference namespace ${fullNamespaceName}`, {lower: true, strict: true});
    addFrontMatterProperty(formFile, `slug: "${formDocSlug}"`);
}

function moveFolder(source, destination) {
    // Ensure the destination directory exists
    const destinationDir = path.dirname(destination);
    if (!fs.existsSync(destinationDir)) {
        fs.mkdirSync(destinationDir, { recursive: true });
    }

    // Move the folder
    fs.renameSync(source, destination);
    console.log(`Folder moved from ${source} to ${destination}`);
}

function fixLinks(folder) {
    fs.readdirSync(folder, { withFileTypes: true })
      .forEach(f => {
          if (f.isDirectory()) {
              fixLinks(folder + '/' + f.name);
          } else {
              console.log(`file: ${folder}/${f.name}`);
              //[success](LiquidExtensionResult.md#success)
              let content = fs.readFileSync(`${folder}/${f.name}`, 'utf8')
              content = content.replaceAll("globals.md", "README.md");

              let linkRe = /\]\(([^\)]*\.md)/g;
              let m;
              do {
                  m = linkRe.exec(content);
                  if (m) {
                      let link = m[1];
                      console.log(`link ${link}`);
                      let targetSlug = getFrontMatterProperty(folder + "/" + link, "slug");
                      console.log(`Replacing ${link} with ${targetSlug}`);
                      content = content.replaceAll(m[1], targetSlug);
                  }
              } while (m);

              fs.writeFileSync(`${folder}/${f.name}`, content);
          }
      });
}

function removeEmptyFolders(folder) {
    if (!fs.existsSync(folder)) return;

    // Read the contents of the folder
    const files = fs.readdirSync(folder);

    // Recursively remove empty subfolders
    files.forEach(file => {
        const fullPath = path.join(folder, file);
        if (fs.statSync(fullPath).isDirectory()) {
            removeEmptyFolders(fullPath);
        }
    });

    // Check if the folder is empty after processing subfolders
    if (fs.readdirSync(folder).length === 0) {
        fs.rmdirSync(folder);
        console.log(`Removed empty folder: ${folder}`);
    }
}

mergeReadmeAndGlobals();
addFrontMatterProperty('./docs/README.md', `order: 10`);
removeFrontMatterProperty('./docs/README.md', 'title');
addFrontMatterProperty('./docs/README.md', 'title: "Overview"');
let overviewSlug = slugify(`node-sdk API reference overview`, {lower: true, strict: true});
addFrontMatterProperty('./docs/README.md', `slug: "${overviewSlug}"`);

createFolderAndMoveDocs('docs', 'variables', 'global', 'Variables');
createFolderAndMoveDocs('docs', 'classes', 'global', 'Classes');

const odpDir = 'ODP-Node-SDK/namespaces/ODP';

flattenNamespace(odpDir, 'ODP', 'ODP');

createFolderAndMoveDocs(`./docs/${odpDir}`, 'classes', 'ODP', 'ODP - Classes');
createFolderAndMoveDocs(`./docs/${odpDir}`, 'interfaces', 'ODP', 'ODP - Interfaces');
createFolderAndMoveDocs(`./docs/${odpDir}`, 'type-aliases', 'ODP', 'ODP - Types');

const apiV3Dir = `${odpDir}/namespaces/ApiV3`;
flattenNamespace(apiV3Dir, 'ApiV3', 'ODP.ApiV3');
createFolderAndMoveDocs(`./docs/${apiV3Dir}`, 'classes', 'ODP.ApiV3', 'ODP.ApiV3 - Classes');
createFolderAndMoveDocs(`./docs/${apiV3Dir}`, 'enumerations', 'ODP.ApiV3', 'ODP.ApiV3 - Enums');
createFolderAndMoveDocs(`./docs/${apiV3Dir}`, 'interfaces', 'ODP.ApiV3', 'ODP.ApiV3 - Interfaces');
createFolderAndMoveDocs(`./docs/${apiV3Dir}`, 'type-aliases', 'ODP.ApiV3', 'ODP.ApiV3 - Types');
createFolderAndMoveDocs(`./docs/${apiV3Dir}`, 'variables', 'ODP.ApiV3', 'ODP.ApiV3 - Variables');

addFrontMatterProperty('./docs/variables.md', `order: 20`);

addFrontMatterProperty(`./docs/${odpDir}/README.md`, `order: 30`);
addFrontMatterProperty(`./docs/${odpDir}/classes.md`, `order: 40`);
addFrontMatterProperty(`./docs/${odpDir}/interfaces.md`, `order: 50`);
addFrontMatterProperty(`./docs/${odpDir}/type-aliases.md`, `order: 60`);

addFrontMatterProperty(`./docs/${apiV3Dir}/README.md`, `order: 70`);
addFrontMatterProperty(`./docs/${apiV3Dir}/classes.md`, `order: 80`);
addFrontMatterProperty(`./docs/${apiV3Dir}/enumerations.md`, `order: 90`);
addFrontMatterProperty(`./docs/${apiV3Dir}/interfaces.md`, `order: 110`);
addFrontMatterProperty(`./docs/${apiV3Dir}/type-aliases.md`, `order: 120`);
addFrontMatterProperty(`./docs/${apiV3Dir}/variables.md`, `order: 130`);

fixLinks('docs');

moveFolder(`./docs/${odpDir}`, './docs/ODP');
moveFolder(`./docs/ODP/namespaces/ApiV3`, './docs/ODP/ApiV3');
removeEmptyFolders('docs');
