name: PR watcher

on: pull_request

jobs:
  build:
    - name: Determinate node version based on major version from package.json
      run: .github/scripts/determine-node-version.sh

    - uses: ./.github/workflows/reusable-build.yaml
      secrets:
        nodeAuthToken: ${{ secrets.GITHUB_TOKEN }}
      with:
        nodeVersion: ${{ env.node_version }}
