name: PR watcher

on:
  pull_request

jobs:
  build:
    - name: Determinate node version based on major version from package.json
      id: extract_node_version
      run: |
        VERSION=$(jq -r '.version' package.json)
        MAJOR_VERSION=$(echo "VERSION" | cut -d '.' -f 1')
        NODE_VERSION=$(echo "MAJOR_VERSION" == '0' && '12.x' || '18.x')
        echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT

    - uses: ./.github/workflows/reusable-build.yaml
      needs: extract_node_version
      secrets:
        nodeAuthToken: ${{ secrets.GITHUB_TOKEN }}
      with:
        nodeVersion: ${{ needs.extract_node_version.outputs.node_version }}
