name: PR watcher

on:
  pull_request

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yaml
    secrets:
      nodeAuthToken: ${{ secrets.GITHUB_TOKEN }}
    with:
      nodeVersion: ${{
        github.event.pull_request.base.ref == '0.x' && '12.x' || '18.x'
      }}
