name: PR watcher

on:
  pull_request

jobs:
  build:
    name: PR watcher
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: yarn
        run: yarn
      - name: lint
        run: yarn run lint
      - name: test
        run: yarn test -- --coverage
      - name: build
        run: yarn run build
