name: reusable-build

on:
  workflow_call:
    inputs:
      nodeVersion:
        description: 'Node JS version to use'
        type: string
        default: '18.x'
        required: true
    secrets:
      nodeAuthToken:
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: ${{ inputs.nodeVersion }}
          registry-url: https://npm.pkg.github.com
          scope: '@zaiusinc'

      - name: yarn
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.nodeAuthToken }}

      - name: lint
        run: yarn run lint

      - name: build
        run: yarn run build

      - name: test
        run: yarn test
